// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GooseDBVersion string
	Package        string
	Tuser          string
	Xnode          string
}{
	GooseDBVersion: "goose_db_version",
	Package:        "package",
	Tuser:          "tuser",
	Xnode:          "xnode",
}
