package xpanels

import (
	"io"
)

// SubRenovator receive an original sub link generated by panels and then modify
// the necessary parts based on available rules
type SubRenovator interface {
	Renovate(reader io.Reader) (string, error)
}
